### ISSUE TITLE
Why not directly from LevelDOWN?

### ISSUE THREAD

**Issue by brycebaril** [miketheprogrammer/level-stream-iterator#1]
Hi @miketheprogrammer -- just wondering why you didn't just use the existing iterator interface you can access from the internal LevelDOWN container under a levelup instance?

e.g. 

``` js
var db = level("./foo.db")
var iterator = db.db.iterator(options)
iterator.next(...)
// etc.
```

**Comment by miketheprogrammer** [comment]
Oh wow. I honestly did not even know that it was exposed via levelup. However what if you want to use the LevelUp interface with a different backend. Would this module be useful then? Except that Abstact Leveldown seems to also cover that AbstractLevelDOWN#_iterator(options)

What do you recommend, should i scrap this. Or does it have use in terms of being a levelup style addon, rather than dealing with the lower level api's.

**Comment by brycebaril** [comment]
I think there is still value to a library like this, but it might be easier/faster if you handled the abstraction vs. people directly digging into LevelDOWN. The other thing that could be handy is you have to be very careful doing what I said that the database is open -- if it isn't you'll segfault if you try and use the iterator. A library like this could provide a safe, easy interface to do so. The other thing you lose going direct to LevelDOWN is any sort of value or key encoding options.

Getting these things correct is definitely enough to justify a module such as this. By wrapping ReadStream you get them both right now, but you might get some performance and clarity benefits if you directly wrapped iterator.

**Comment by miketheprogrammer** [comment]
Closing the issue. Plans are to build out a successful interface on top of readstream. Later roadmap to improve based on level down. Probably detect if leveldown is the backend, otherwise just use the backends implementation of readStream. 

@brycebaril Feel free to contribute in any way if you find the project interesting, and have the time. And thanks for the feedback.

**Comment by brycebaril** [comment]
Sounds good :)
